version: "3.8"
services:
  drone1:
    build: ./ai
    environment:
      - SOURCE_URL=http://10.217.7.149:8080/cameras/0
    ports:
      - "8001:8000"

  drone2:
    build: ./ai
    environment:
      - SOURCE_URL=http://10.217.7.149:8080/cameras/1
    ports:
      - "8002:8000"

  drone3:
    build: ./ai
    environment:
      - SOURCE_URL=http://10.217.7.149:8080/cameras/2
    ports:
      - "8003:8000"

  drone4:
    build: ./ai
    environment:
      - SOURCE_URL=http://10.217.7.149:8080/cameras/3
    ports:
      - "8004:8000"

  drone5:
    build: ./ai
    environment:
      - SOURCE_URL=http://10.217.7.149:8080/cameras/4
    ports:
      - "8005:8000"
