version: "3.8"
services:
  server:
    build: ./server
    networks:
      - custom_network
    ports:
      - "80:80"

  drone1:
    build: ./ai
    networks:
      - custom_network
    environment:
      - SOURCE_URL=http://10.217.7.149:8080/cameras/0
      - DRONE=0
    ports:
      - "8001:8000"

  drone2:
    build: ./ai
    networks:
      - custom_network
    environment:
      - SOURCE_URL=http://10.217.7.149:8080/cameras/1
      - DRONE=1
    ports:
      - "8002:8000"

  drone3:
    build: ./ai
    networks:
      - custom_network
    environment:
      - SOURCE_URL=http://10.217.7.149:8080/cameras/2
      - DRONE=2
    ports:
      - "8003:8000"

  # drone4:
  #   build: ./ai
  #   networks:
  #     - custom_network
  #   environment:
  #     - SOURCE_URL=http://10.217.7.149:8080/cameras/3
  #     - DRONE=3
  #   ports:
  #     - "8004:8000"

  # drone5:
  #   build: ./ai
  #   networks:
  #     - custom_network
  #   environment:
  #     - SOURCE_URL=http://10.217.7.149:8080/cameras/4
  #     - DRONE=4
  #   ports:
  #     - "8005:8000"

networks:
  custom_network:
    driver: bridge
